from pydantic import BaseModel, ConfigDict

CUSTOM_VALIDATION_ERROR_MESSAGES = {
    'arguments_type': 'Parameter type input error',
    'assertion_error': 'Assertion execution error',
    'bool_parsing': 'Boolean input parsing error',
    'bool_type': 'Boolean type input error',
    'bytes_too_long': 'Byte length input is too long',
    'bytes_too_short': 'Byte length input is too short',
    'bytes_type': 'Byte type input error',
    'callable_type': 'Incorrect callable object type',
    'dataclass_exact_type': 'Data class instance type input error',
    'dataclass_type': 'Data class type input error',
    'date_from_datetime_inexact': 'Date component input is non-zero',
    'date_from_datetime_parsing': 'Date input parsing error',
    'date_future': 'Date input is not in future tense',
    'date_parsing': 'Date input validation error',
    'date_past': 'Date input is not past tense',
    'date_type': 'Date type input error',
    'datetime_future': 'Date time input is not a future time',
    'datetime_object_invalid': 'The date and time input object is invalid',
    'datetime_parsing': 'Datetime input parsing error',
    'datetime_past': 'Date time input is not in the past time',
    'datetime_type': 'Datetime type input error',
    'decimal_max_digits': 'Enter too many decimal digits',
    'decimal_max_places': 'Wrong input of decimal places',
    'decimal_parsing': 'Decimal input parsing error',
    'decimal_type': 'Decimal type input error',
    'decimal_whole_digits': 'Wrong number of decimal places entered',
    'dict_type': 'Dictionary type input error',
    'enum': 'Enumeration member input error, {expected} allowed',
    'extra_forbidden': 'Forbid extra fields to be entered',
    'finite_number': 'Input error of finite value',
    'float_parsing': 'Floating point input parsing error',
    'float_type': 'Floating point type input error',
    'frozen_field': 'Input error in frozen field',
    'frozen_instance': 'Frozen instance prohibits modification',
    'frozen_set_type': 'Frozen type prohibits input',
    'get_attribute_error': 'Get attribute error',
    'greater_than': 'The input value is too large',
    'greater_than_equal': 'The input value is too large or equal',
    'int_from_float': 'Integer type input error',
    'int_parsing': 'Integer input parsing error',
    'int_parsing_size': 'Integer input parsing length error',
    'int_type': 'Integer type input error',
    'invalid_key': 'Enter invalid key value',
    'is_instance_of': 'Type instance input error',
    'is_subclass_of': 'Type subclass input error',
    'iterable_type': 'Iterable type input error',
    'iteration_error': 'Iteration value input error',
    'json_invalid': 'JSON string input error',
    'json_type': 'JSON type input error',
    'less_than': 'The input value is too small',
    'less_than_equal': 'The input value is too small or equal',
    'list_type': 'List type input error',
    'literal_error': 'Literal value input error',
    'mapping_type': 'Mapping type input error',
    'missing': 'Missing required fields',
    'missing_argument': 'Missing argument',
    'missing_keyword_only_argument': 'Missing keyword argument',
    'missing_positional_only_argument': 'Missing positional argument',
    'model_attributes_type': 'Model attribute type input error',
    'model_type': 'Model instance input error',
    'multiple_argument_values': 'Too many parameter values entered',
    'multiple_of': 'The input value is not a multiple',
    'no_such_attribute': 'Assign invalid attribute value',
    'none_required': 'The input value must be None',
    'recursion_loop': 'Input loop assignment',
    'set_type': 'Set type input error',
    'string_pattern_mismatch': 'String constraint pattern input does not match',
    'string_sub_type': 'String subtype (non-strict instance) input error',
    'string_too_long': 'String input is too long',
    'string_too_short': 'String input is too short',
    'string_type': 'String type input error',
    'string_unicode': 'String input is not Unicode',
    'time_delta_parsing': 'Time difference input parsing error',
    'time_delta_type': 'Time difference type input error',
    'time_parsing': 'Time input parsing error',
    'time_type': 'Time type input error',
    'timezone_aware': 'Missing time zone input information',
    'timezone_naive': 'Prohibit time zone input information',
    'too_long': 'Input too long',
    'too_short': 'Input too short',
    'tuple_type': 'Tuple type input error',
    'unexpected_keyword_argument': 'Enter unexpected keyword argument',
    'unexpected_positional_argument': 'Input unexpected positional argument',
    'union_tag_invalid': 'Union type literal input error',
    'union_tag_not_found': 'Union type parameter input not found',
    'url_parsing': 'URL input parsing error',
    'url_scheme': 'URL input scheme error',
    'url_syntax_violation': 'URL input syntax error',
    'url_too_long': 'URL input is too long',
    'url_type': 'URL type input error',
    'uuid_parsing': 'UUID input parsing error',
    'uuid_type': 'UUID type input error',
    'uuid_version': 'UUID version type input error',
    'value_error': 'Value input error',
}

CUSTOM_USAGE_ERROR_MESSAGES = {
    'class-not-fully-defined': 'Class attribute type is not fully defined',
    'custom-json-schema': '__modify_schema__ method has been deprecated in V2',
    'decorator-missing-field': 'Invalid field validator defined',
    'discriminator-no-field': 'The discriminator fields are not all defined',
    'discriminator-alias-type': 'The discriminator field is defined using a non-string type',
    'discriminator-needs-literal': 'The discriminator field needs to be defined using literal values',
    'discriminator-alias': 'Discriminator field alias definition is inconsistent',
    'discriminator-validator': 'The discriminator field prohibits defining field validators',
    'model-field-overridden': 'Untyped fields prohibit overriding',
    'model-field-missing-annotation': 'Missing field type definition',
    'config-both': 'Repeatly define configuration items',
    'removed-kwargs': 'Calling removed keyword configuration parameters',
    'invalid-for-json-schema': 'Invalid JSON type exists',
    'base-model-instantiated': 'Prohibit instantiating the base model',
    'undefined-annotation': 'Missing type definition',
    'schema-for-unknown-type': 'Unknown type definition',
    'create-model-field-definitions': 'Field definition error',
    'create-model-config-base': 'Configuration item definition error',
    'validator-no-fields': 'Field validator does not specify fields',
    'validator-invalid-fields': 'Field validator field definition error',
    'validator-instance-method': 'Field validator must be a class method',
    'model-serializer-instance-method': 'The serializer must be an instance method',
    'validator-v1-signature': 'V1 field validator error has been deprecated',
    'validator-signature': 'Field validator signature error',
    'field-serializer-signature': 'Field serializer signature cannot be recognized',
    'model-serializer-signature': 'The model serializer signature cannot be recognized',
    'multiple-field-serializers': 'Field serializers are repeatedly defined',
    'invalid_annotated_type': 'Invalid type definition',
    'type-adapter-config-unused': 'Type adapter configuration item definition error',
    'root-model-extra': 'The root model is prohibited from defining additional fields',
}


class SchemaBase(BaseModel):
    model_config = ConfigDict(use_enum_values=True, arbitrary_types_allowed=True, from_attributes=True)